Repository gitcoinco/grants-stack, pull requests merged in 2023-12, with the labels that each got.

#2679 chore: try new PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1 min review, missing-tests, safe-change

#2696 remove default value from controller component and fix svg attribute names
  packages/grant-explorer/src/features/common/Navbar.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx
Labels: 1 min review, missing-tests

#2725 Remove one of the ACS rounds from explorer homepage
  packages/grant-explorer/src/features/api/rounds.ts
Labels: 1 min review, missing-tests

#2662 Insufficient funds handling
  package.json
  packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/Summary.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  pnpm-lock.yaml
Labels: missing-tests, 5 min review

#2743 chore: remove wconnect temporarily to guard against ledger drainerˆ
  packages/builder/src/components/Header.tsx
  packages/builder/src/utils/wagmi.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/src/app/wagmi.ts
  packages/round-manager/package.json
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/common/Navbar.tsx
  pnpm-lock.yaml
Labels: missing-tests, 20 min review

#2745 Revert "chore: remove wconnect temporarily to guard against ledger dr…
  packages/builder/src/components/Header.tsx
  packages/builder/src/utils/wagmi.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/src/app/wagmi.ts
  packages/round-manager/package.json
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/common/Navbar.tsx
  pnpm-lock.yaml
Labels: missing-tests, 5 min review

#2665 chore: simplify payout tokens handling
  packages/round-manager/src/context/application/usePayout.ts
  packages/round-manager/src/context/round/FundContractContext.tsx
  packages/round-manager/src/context/round/UpdateRoundContext.tsx
  packages/round-manager/src/features/api/application.ts
  packages/round-manager/src/features/api/payoutTokens.ts
  packages/round-manager/src/features/api/round.ts
  packages/round-manager/src/features/api/utils.ts
  packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
  packages/round-manager/src/features/round/FundContract.tsx
  packages/round-manager/src/features/round/QuadraticFundingForm.tsx
  packages/round-manager/src/features/round/ReclaimFunds.tsx
  packages/round-manager/src/features/round/ViewFundGrantees.tsx
  packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
  packages/round-manager/src/features/round/ViewRoundStats.tsx
  packages/round-manager/src/features/round/__tests__/QuadraticFundingForm.test.tsx
Labels: 20 min review

#2731 Migrate rounds and passport query to data layer
  packages/data-layer/.eslintrc.json
  packages/data-layer/package.json
  packages/data-layer/src/backends/legacy.test.ts
  packages/data-layer/src/backends/legacy.ts
  packages/data-layer/src/data-layer.test.ts
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data-layer.types.ts
  packages/data-layer/src/data.types.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/src/cartStore.test.tsx
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/features/discovery/ActiveRoundSection.tsx
  packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
  packages/grant-explorer/src/features/discovery/FilterDropdown.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/RoundsFilter.tsx
  packages/grant-explorer/src/features/discovery/RoundsGrid.tsx
  packages/grant-explorer/src/features/discovery/SortDropdown.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/__tests__/useFilterRounds.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts
  packages/grant-explorer/src/features/discovery/utils/__tests__/getExplorerPageTitle.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getFilterLabel.test.tsx
  packages/grant-explorer/src/features/discovery/utils/createRoundLoadingData.ts
  packages/grant-explorer/src/features/discovery/utils/createRoundsStatusFilter.ts
  packages/grant-explorer/src/features/discovery/utils/getExplorerPageTitle.ts
  packages/grant-explorer/src/features/discovery/utils/getFilterLabel.ts
  packages/grant-explorer/src/features/discovery/utils/getSortLabel.ts
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
  packages/grant-explorer/src/test-utils.tsx
  pnpm-lock.yaml
Labels: 20 min review

#2748 gg19 cleanup
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/index.tsx
Labels: 1 min review

#2752 fix: don't hide "apply" button before application end time
  packages/grant-explorer/src/features/api/__tests__/utils.test.tsx
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/RoundTimeBadge.tsx
Labels: 5 min review

#2753 feat: update numbers on main page
  packages/grant-explorer/src/features/discovery/LandingHero.tsx
Labels: 1 min review, missing-tests

#2754 feat: clear projects from expired rounds from cart
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
Labels: 1 min review, missing-tests

#2726 Add zksync mainnet & testnet support
  packages/builder/.env.example
  packages/builder/.env.test
  packages/builder/package.json
  packages/builder/src/actions/roundApplication.ts
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/utils/chains.ts
  packages/builder/src/utils/wallet.ts
  packages/common/.env.test
  packages/common/src/chain-ids.ts
  packages/common/src/chains.ts
  packages/common/src/config.ts
  packages/common/src/icons/zksync-logo.svg
  packages/common/src/index.ts
  packages/grant-explorer/.env.example
  packages/grant-explorer/.env.test
  packages/grant-explorer/public/logos/lusd-logo.svg
  packages/grant-explorer/public/logos/mute-logo.svg
  packages/grant-explorer/public/logos/usdt-logo.svg
  packages/grant-explorer/public/logos/zksync-logo.svg
  packages/grant-explorer/src/app/chainConfig.ts
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/.env.example
  packages/round-manager/.env.test
  packages/round-manager/package.json
  packages/round-manager/public/logos/lusd-logo.svg
  packages/round-manager/public/logos/mute-logo.svg
  packages/round-manager/public/logos/usdt-logo.svg
  packages/round-manager/public/logos/zksync-logo.svg
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/payoutTokens.ts
  packages/round-manager/src/features/api/utils.ts
  pnpm-lock.yaml
Labels: missing-tests, 10 min review

#2737 Add Base mainnet as a network on Grants Stack
  packages/builder/.env.example
  packages/builder/.env.test
  packages/builder/package.json
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/utils/chains.ts
  packages/builder/src/utils/wallet.ts
  packages/common/.env.test
  packages/common/package.json
  packages/common/src/chain-ids.ts
  packages/common/src/chains.ts
  packages/common/src/config.ts
  packages/common/src/icons/base-logo.svg
  packages/common/src/index.ts
  packages/grant-explorer/.env.example
  packages/grant-explorer/.env.test
  packages/grant-explorer/public/logos/base-logo.svg
  packages/grant-explorer/src/app/chainConfig.ts
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/.env.test
  packages/round-manager/package.json
  packages/round-manager/public/logos/base-logo.svg
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/payoutTokens.ts
  packages/round-manager/src/features/api/utils.ts
  pnpm-lock.yaml
Labels: missing-tests, 20 min review
