Repository gitcoinco/grants-stack, pull requests merged in 2023-09, with the labels that each got.

#2266 feat: add arbitrum to apps
  .github/workflows/grant-explorer.yml
  packages/builder/package.json
  packages/builder/src/assets/icons/arb-logo.svg
  packages/builder/src/assets/index.ts
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/utils/graphql.ts
  packages/builder/src/utils/wagmi.ts
  packages/builder/src/utils/wallet.ts
  packages/common/src/chains.ts
  packages/common/src/index.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/public/logos/arb-logo.svg
  packages/grant-explorer/src/app/wagmi.ts
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/discovery/ActiveRoundSection.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/round-manager/.env.sample
  packages/round-manager/package.json
  packages/round-manager/public/logos/arb-logo.svg
  packages/round-manager/public/logos/gcv.svg
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/utils.ts
  pnpm-lock.yaml
Labels: missing-tests, 20 min review

#2290 hotfix cart
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  packages/grant-explorer/src/store.ts
Labels: 1 min review, missing-tests

#2219 fix: fix build
  .github/workflows/builder.yml
  .github/workflows/grant-explorer.yml
  .github/workflows/round-manager.yml
  package.json
  packages/builder/package.json
  packages/eslint-config-gitcoin/package.json
  packages/grant-explorer/package.json
  packages/round-manager/package.json
  packages/round-manager/src/app/store.ts
  packages/round-manager/src/history.ts
  packages/round-manager/src/index.tsx
  packages/round-manager/src/test-utils.tsx
  pnpm-lock.yaml
Labels: 20 min review

#2319 fix connect wallet bug by enabling sourcemaps
  packages/builder/craco.config.js
  packages/builder/tsconfig.json
Labels: 1 min review, missing-tests

#2315 feat: add GTC as a payout token in Manager
  packages/common/src/index.ts
  packages/round-manager/public/logos/gtc.svg
  packages/round-manager/src/features/api/utils.ts
Labels: 1 min review, missing-tests

#2324 fix: pull token info from chain on explorer
  packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/__tests__/ApplyNowSection.test.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
  turbo.json
Labels: 5 min review

#2339 ignore, testing github actions
  .github/workflows/builder.yml
Labels: 5 min review

#2333 fix: rename arbitrum one to arbitrum for lit js sdk
  .github/workflows/builder.yml
  package.json
  packages/grant-explorer/src/features/api/__tests__/utils.test.tsx
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/src/features/api/__tests__/utils.test.ts
  packages/round-manager/src/features/api/utils.ts
  packages/round-manager/src/features/round/ViewApplicationPage.tsx
Labels: 5 min review

#2330 fix: fixed typo in RoundDetailForm.
  packages/round-manager/src/features/round/RoundDetailForm.tsx
Labels: 1 min review, missing-tests

#2346 feat: new active rounds section in secondary navbar
  packages/common/src/components/RoundsSubNav.tsx
  packages/grant-explorer/src/features/common/Navbar.tsx
  packages/grant-explorer/src/features/common/__tests__/Navbar.test.tsx
  packages/grant-explorer/src/features/discovery/RoundsSubNav.tsx
Labels: 5 min review

#2350 chore: add usdc info on polygon pos
  docs/TOKENS.md
Labels: 1 min review, missing-tests, safe-change

#2326 fix: Fixed typo in Round Application form
  packages/round-manager/src/features/round/RoundApplicationForm.tsx
Labels: 1 min review, missing-tests

#2331 fix: fixed avg contribution calc + NaN state display on Manager
  packages/round-manager/src/features/round/ViewRoundStats.tsx
Labels: 1 min review, missing-tests

#2365 check env var is "true"
  packages/builder/src/utils/wagmi.ts
Labels: 1 min review, missing-tests

#2363 chore: add polygon & mumbai support
  docs/TOKENS.md
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/utils/graphql.ts
  packages/builder/src/utils/wagmi.ts
  packages/builder/src/utils/wallet.ts
  packages/common/src/chains.ts
  packages/common/src/icons/pol-logo.svg
  packages/common/src/index.ts
  packages/grant-explorer/public/logos/pol-logo.svg
  packages/grant-explorer/src/app/chainConfig.ts
  packages/grant-explorer/src/app/wagmi.ts
  packages/grant-explorer/src/cartStore.test.tsx
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/types.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/api/voting.ts
  packages/grant-explorer/src/features/contributors/DonationsTable.tsx
  packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
  packages/grant-explorer/src/features/contributors/__tests__/ViewContributionHistory.test.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/round/ViewCartPage.ignored.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ConfirmationModalBody.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/PayoutTokenButton.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/PayoutTokenDropdown.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/Summary.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
  packages/grant-explorer/src/store.ts
  packages/round-manager/public/logos/pol-logo.svg
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/utils.ts
  packages/verify-env/src/WebpackPlugin.ts
  packages/verify-env/src/testSource.txt
  packages/verify-env/src/verify.ts
Labels: 10 min review

#2327 fix: Updated link in the public/private question to be explorer.gitco…
  packages/round-manager/src/features/round/RoundDetailForm.tsx
Labels: 1 min review, missing-tests

#2372 feat: make cart handle new chains gracefully
  packages/grant-explorer/src/cartStore.test.tsx
  packages/grant-explorer/src/checkoutStore.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  packages/grant-explorer/src/store.ts
  pnpm-lock.yaml
Labels: 5 min review

#2351 chore: add avax & fuji support
  lefthook.yml
  package.json
  packages/builder/package.json
  packages/builder/src/components/application/AboutProject.tsx
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/utils/utils.ts
  packages/builder/src/utils/wagmi.ts
  packages/builder/src/utils/wallet.ts
  packages/common/src/chains.ts
  packages/common/src/icons/AVAX.svg
  packages/common/src/index.ts
  packages/grant-explorer/public/logos/avax-logo.svg
  packages/grant-explorer/src/app/chainConfig.ts
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/public/logos/avax-logo.svg
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/utils.ts
  packages/round-manager/src/features/round/RoundDetailForm.tsx
  pnpm-lock.yaml
Labels: missing-tests, 20 min review

#2402 hotfix: temporarily handle direct grant rounds
  packages/common/src/index.ts
Labels: 1 min review, missing-tests
