Repository gitcoinco/grants-stack, pull requests merged in 2023-08, with the labels that each got.

#2238 Add gitstream
  .cm/approve_js_formatting.cm
  .cm/approve_js_log_changes.cm
  .cm/approve_tests.cm
  .cm/code_experts.cm
  .cm/estimated_time_to_review.cm
  .cm/label_without_tests.cm
  .cm/percentage_new_code.cm
  .cm/safe_changes.cm
  .github/workflows/gitstream.yml
Labels: engineering, cm-changes

#2239 update codeowners with the new team names
  CODEOWNERS
Labels: 1 min review, missing-tests

#2254 find token by address and chainId
  packages/round-manager/src/features/api/utils.ts
  packages/round-manager/src/features/round/FundContract.tsx
Labels: 1 min review, missing-tests

#2248 add arbitrum round link to gg18 subnav
  packages/common/src/components/RoundsSubNav.tsx
Labels: 1 min review, missing-tests

#2224 MRC: Mobile UI fixes on cart page
  packages/grant-explorer/src/assets/thank-you.svg
  packages/grant-explorer/src/features/round/ThankYou.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ApplyTooltip.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/CartWithProjects.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ProjectInCart.tsx
Labels: 1 min review, missing-tests

#2277 fix: eth -> ftm token
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
  packages/round-manager/src/features/round/ViewRoundStats.tsx
Labels: 1 min review, missing-tests

#2256 remove manifest from Builder
  packages/builder/public/index.html
  packages/builder/public/manifest.json
Labels: 1 min review, missing-tests

#2279 fix: eth -> ftm on explorer running round page
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/common/__tests__/CopyToClipboardButton.test.tsx
Labels: 1 min review

#2247 Port tests to vitest and add new tests
  docs/DAI.md
  packages/common/src/components/RoundsSubNav.tsx
  packages/grant-explorer/package.json
  packages/grant-explorer/src/cartStore.test.tsx
  packages/grant-explorer/src/checkoutStore.test.tsx
  packages/grant-explorer/src/checkoutStore.ts
  packages/grant-explorer/src/context/__tests__/RoundContext.test.tsx
  packages/grant-explorer/src/features/api/LocalStorage.ts
  packages/grant-explorer/src/features/api/__tests__/localstorage.test.ts
  packages/grant-explorer/src/features/api/__tests__/passport.test.tsx
  packages/grant-explorer/src/features/api/__tests__/round.test.tsx
  packages/grant-explorer/src/features/api/__tests__/subgraph.test.tsx
  packages/grant-explorer/src/features/api/__tests__/utils.test.tsx
  packages/grant-explorer/src/features/api/__tests__/voting.test.tsx
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/api/voting.ts
  packages/grant-explorer/src/features/common/CartNotification.tsx
  packages/grant-explorer/src/features/common/ErrorModal.tsx
  packages/grant-explorer/src/features/common/ProgressModal.tsx
  packages/grant-explorer/src/features/common/RoundEndedBanner.tsx
  packages/grant-explorer/src/features/common/SearchInput.tsx
  packages/grant-explorer/src/features/common/__tests__/CartNotification.test.tsx
  packages/grant-explorer/src/features/common/__tests__/ConfirmationModal.test.tsx
  packages/grant-explorer/src/features/common/__tests__/CopyToClipboardButton.test.tsx
  packages/grant-explorer/src/features/common/__tests__/ErrorModal.test.tsx
  packages/grant-explorer/src/features/common/__tests__/InfoModal.test.tsx
  packages/grant-explorer/src/features/common/__tests__/Navbar.test.tsx
  packages/grant-explorer/src/features/common/__tests__/NavbarCart.test.tsx
  packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx
  packages/grant-explorer/src/features/common/__tests__/ProgressModal.test.tsx
  packages/grant-explorer/src/features/common/__tests__/RoundEndedBanner.test.tsx
  packages/grant-explorer/src/features/common/__tests__/SearchInput.test.tsx
  packages/grant-explorer/src/features/contributors/__tests__/ViewContributionHistory.test.tsx
  packages/grant-explorer/src/features/discovery/ApplyNowSection.tsx
  packages/grant-explorer/src/features/discovery/NoRounds.tsx
  packages/grant-explorer/src/features/discovery/__tests__/ApplyNowSection.test.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/features/discovery/__tests__/NoRounds.test.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
  packages/grant-explorer/src/fileMock.js
  packages/grant-explorer/src/setupTests.ts
  packages/grant-explorer/src/store.ts
  packages/grant-explorer/src/test-utils.tsx
  packages/grant-explorer/tsconfig.json
  packages/grant-explorer/vitest.config.ts
  pnpm-lock.yaml
Labels: 30 min review
