Repository gitcoinco/grants-stack, pull requests merged in 2023-10, with the labels that each got.

#2416 Unable to launch Direct Grants round on Polygon
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/round.ts
Labels: missing-tests, 5 min review

#2399 remove manifest link from Manager
  packages/round-manager/public/index.html
Labels: 1 min review, missing-tests

#2413 make sure pinata requests don't fail if base URL ends with a '/'
  packages/builder/src/services/pinata.ts
Labels: 1 min review, missing-tests

#2400 Update fund contract copy in rm
  packages/round-manager/src/features/round/FundContract.tsx
Labels: 1 min review, missing-tests

#2421 [Manager] Applications CSV download btn is missing
  packages/round-manager/src/features/round/DGApplicationsToApproveReject.tsx
  packages/round-manager/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/round/__tests__/DGApplicationsToApproveReject.test.tsx
Labels: 1 min review

#2314 enh: run code checks in pre-commit and pre-push hooks
  .prettierignore
  lefthook.yml
  package.json
  packages/builder/package.json
  packages/eslint-config-gitcoin/index.js
  packages/eslint-config-gitcoin/package.json
  packages/grant-explorer/package.json
  packages/round-manager/.prettierignore
  packages/round-manager/package.json
  packages/round-manager/src/features/round/RoundDetailForm.tsx
  packages/round-manager/src/features/round/ViewRoundStats.tsx
  packages/round-manager/tsconfig.json
  packages/verify-env/src/index.test.ts
  pnpm-lock.yaml
Labels: 10 min review

#2432 fix dg applications received bug
  packages/round-manager/src/features/round/ApplicationsToApproveReject.tsx
  packages/round-manager/src/features/round/ApplicationsToReview.tsx
  packages/round-manager/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/round/__tests__/ApplicationsToApproveReject.test.tsx
Labels: 5 min review

#2434 chore: add PR checklist to pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1 min review, missing-tests, safe-change

#2424 add the PowerPool token (CVP) in the payout tokens
  packages/common/src/index.ts
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/round-manager/public/logos/power-pool.png
  packages/round-manager/src/context/application/usePayout.ts
  packages/round-manager/src/features/api/utils.ts
  packages/round-manager/src/features/common/AddQuestionModal.tsx
  packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
  packages/round-manager/src/features/round/RoundApplicationForm.tsx
Labels: missing-tests, 5 min review

#2443 docs: update .env.examples
  packages/builder/.env.example
  packages/grant-explorer/.env.example
  packages/round-manager/.env.example
Labels: 1 min review, missing-tests

#2447 fix incorrect token name on Donation History page
  packages/grant-explorer/src/features/contributors/DonationsTable.tsx
  packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
Labels: 1 min review, missing-tests

#2448 Make the Application Detail and Amount requested questions optional
  packages/round-manager/src/features/round/RoundApplicationForm.tsx
Labels: 1 min review, missing-tests

#2440 docs: update contributing docs
  .github/PULL_REQUEST_TEMPLATE.md
  CONTRIBUTING.md
  README.md
  docs/DEV.md
  docs/KB.md
  packages/builder/README.md
  packages/grant-explorer/docs/DEV.md
  packages/round-manager/README.md
  packages/round-manager/docs/DEV.md
Labels: missing-tests, 5 min review

#2465 chore: remove REACT_APP_DIRECT_GRANT_ENABLED and make it the default
  packages/round-manager/.env.example
  packages/round-manager/src/features/program/ViewProgramPage.tsx
Labels: missing-tests, 5 min review

#2463 [2383] Round card redesign
  packages/grant-explorer/src/assets/landing/stock1.jpg
  packages/grant-explorer/src/assets/landing/stock10.jpg
  packages/grant-explorer/src/assets/landing/stock11.jpg
  packages/grant-explorer/src/assets/landing/stock12.jpg
  packages/grant-explorer/src/assets/landing/stock13.jpg
  packages/grant-explorer/src/assets/landing/stock14.jpg
  packages/grant-explorer/src/assets/landing/stock15.jpg
  packages/grant-explorer/src/assets/landing/stock16.jpg
  packages/grant-explorer/src/assets/landing/stock17.jpg
  packages/grant-explorer/src/assets/landing/stock18.jpg
  packages/grant-explorer/src/assets/landing/stock19.jpg
  packages/grant-explorer/src/assets/landing/stock2.jpg
  packages/grant-explorer/src/assets/landing/stock20.jpg
  packages/grant-explorer/src/assets/landing/stock21.jpg
  packages/grant-explorer/src/assets/landing/stock22.jpg
  packages/grant-explorer/src/assets/landing/stock23.jpg
  packages/grant-explorer/src/assets/landing/stock24.jpg
  packages/grant-explorer/src/assets/landing/stock25.jpg
  packages/grant-explorer/src/assets/landing/stock26.jpg
  packages/grant-explorer/src/assets/landing/stock27.jpg
  packages/grant-explorer/src/assets/landing/stock28.jpg
  packages/grant-explorer/src/assets/landing/stock29.jpg
  packages/grant-explorer/src/assets/landing/stock3.jpg
  packages/grant-explorer/src/assets/landing/stock30.jpg
  packages/grant-explorer/src/assets/landing/stock31.jpg
  packages/grant-explorer/src/assets/landing/stock32.jpg
  packages/grant-explorer/src/assets/landing/stock4.jpg
  packages/grant-explorer/src/assets/landing/stock5.jpg
  packages/grant-explorer/src/assets/landing/stock6.jpg
  packages/grant-explorer/src/assets/landing/stock7.jpg
  packages/grant-explorer/src/assets/landing/stock8.jpg
  packages/grant-explorer/src/assets/landing/stock9.jpg
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/common/styles.ts
  packages/grant-explorer/src/features/discovery/RoundBanner.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/RoundCardStat.tsx
  packages/grant-explorer/src/features/discovery/RoundDaysLeft.tsx
  packages/grant-explorer/tailwind.config.js
Labels: missing-tests, 5 min review

#2475 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 1 min review, missing-tests, safe-change

#2483 fix: make project titles visible
  packages/grant-explorer/src/features/common/styles.ts
Labels: 1 min review, missing-tests

#2480 bug: fixed go to passport link in checkout modal returned 404
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
Labels: 1 min review, missing-tests

#2449 Add Passport widget in nav bar in Explorer
  packages/common/package.json
  packages/common/src/index.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/public/modern-era-medium.otf
  packages/grant-explorer/public/modern-era-regular.otf
  packages/grant-explorer/src/assets/passport-logo-bw.svg
  packages/grant-explorer/src/assets/passport-logo-full.svg
  packages/grant-explorer/src/assets/passport-logo.svg
  packages/grant-explorer/src/features/api/__tests__/passport.test.tsx
  packages/grant-explorer/src/features/api/passport.ts
  packages/grant-explorer/src/features/common/MatchingEstimateTooltip.tsx
  packages/grant-explorer/src/features/common/Navbar.tsx
  packages/grant-explorer/src/features/common/Passport.tsx
  packages/grant-explorer/src/features/common/PassportBanner.tsx
  packages/grant-explorer/src/features/common/PassportWidget.tsx
  packages/grant-explorer/src/features/common/__tests__/Navbar.test.tsx
  packages/grant-explorer/src/features/common/__tests__/PassportBanner.test.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/round/PassportConnect.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/features/round/__tests__/PassportConnect.test.tsx
  packages/grant-explorer/src/index.css
  packages/grant-explorer/src/index.tsx
  pnpm-lock.yaml
Labels: 20 min review

#2481 fix: allow non-integers in matching cap in round settings
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
Labels: 1 min review, missing-tests

#2500 fix: concurrency conflict in github actions
  .github/workflows/common.yml
  .github/workflows/verify-env.yml
Labels: 1 min review, missing-tests

#2502 Fix #2501 RoundCard title color
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
Labels: 1 min review, missing-tests

#2507 feat: add dai to pgn
  packages/round-manager/src/features/api/utils.ts
Labels: 1 min review, missing-tests

#2466 fix: don't display testnet rounds in production on expl. homepage
  packages/common/src/chains.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/src/features/api/rounds.ts
  pnpm-lock.yaml
Labels: missing-tests, 5 min review

#2462 fix: added text-area instead of input for multiline input
  packages/common/src/styles.ts
  packages/round-manager/src/features/round/ApplicationEligibilityForm.tsx
Labels: 1 min review, missing-tests

#2513 feat(round-settings): fix visual bugs
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
Labels: 1 min review, missing-tests

#2517 feat(round-settings): fix round time editing bug
  packages/round-manager/package.json
  packages/round-manager/src/context/round/UpdateRoundContext.tsx
  pnpm-lock.yaml
Labels: missing-tests, 5 min review

#2514 fix: silence source map warnings
  packages/builder/craco.config.js
Labels: 1 min review, missing-tests

#2512 Enable round operators to edit the round metadata anytime before the rounds ends in manager
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
Labels: missing-tests, 5 min review

#2523 Add usdc as a payout token on polygon
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/src/features/api/utils.ts
Labels: 1 min review, missing-tests

#2520 Add dai as donation token to pgn on explorer
  packages/grant-explorer/src/features/api/utils.ts
Labels: 1 min review, missing-tests
