Repository gitcoinco/grants-stack, pull requests merged in 2023-11, with the labels that each got.

#2505 initial dev env
  docker-compose.yml
  docs/DEV.md
  packages/builder/.env.example
  packages/builder/.jest/setEnvVars.js
  packages/builder/package.json
  packages/builder/src/actions/grantsMetadata.ts
  packages/builder/src/actions/newGrant.ts
  packages/builder/src/actions/roundApplication.ts
  packages/builder/src/actions/rounds.ts
  packages/builder/src/assets/index.ts
  packages/builder/src/components/base/ImageInput.tsx
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/services/pinata.ts
  packages/builder/src/utils/components.ts
  packages/builder/src/utils/wagmi.ts
  packages/builder/src/utils/wallet.ts
  packages/common/src/assets/fantom-ftm-logo.png
  packages/common/src/chains.ts
  packages/common/src/config.ts
  packages/common/src/index.ts
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/utils.ts
  pnpm-lock.yaml
Labels: missing-tests, 20 min review

#2530 update incorrect chainId for usdc on polgon mumbai testnet
  packages/grant-explorer/src/features/api/utils.ts
Labels: 1 min review, missing-tests

#2533 use a custom rpc config for optimism and polygon to avoid errors from public RPC without api key
  packages/builder/src/utils/wagmi.ts
  packages/common/src/chains.ts
Labels: missing-tests, 5 min review

#2540 override default and public wagmi rpc url in builder
  packages/builder/src/utils/wagmi.ts
  packages/common/src/chains.ts
Labels: missing-tests, 5 min review

#2541 Update getConfig to fix failing tests
  packages/common/src/config.ts
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/test-utils.tsx
Labels: 1 min review

#2529 [2378] Sort and Filter rounds
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/features/common/DefaultLayout.tsx
  packages/grant-explorer/src/features/common/Dropdown.tsx
  packages/grant-explorer/src/features/common/styles.ts
  packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
  packages/grant-explorer/src/features/discovery/FilterDropdown.tsx
  packages/grant-explorer/src/features/discovery/LandingHero.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/LandingSection.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/RoundsEmptyState.tsx
  packages/grant-explorer/src/features/discovery/RoundsFilter.tsx
  packages/grant-explorer/src/features/discovery/RoundsGrid.tsx
  packages/grant-explorer/src/features/discovery/SortDropdown.tsx
  packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts
  packages/grant-explorer/src/features/discovery/utils/__tests__/createRoundsStatusFilter.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getExplorerPageTitle.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getFilterLabel.test.tsx
  packages/grant-explorer/src/features/discovery/utils/createRoundLoadingData.ts
  packages/grant-explorer/src/features/discovery/utils/createRoundsStatusFilter.ts
  packages/grant-explorer/src/features/discovery/utils/getExplorerPageTitle.ts
  packages/grant-explorer/src/features/discovery/utils/getFilterLabel.ts
  packages/grant-explorer/src/features/discovery/utils/getSortLabel.ts
  packages/grant-explorer/src/test-utils.tsx
Labels: 20 min review

#2547 Explorer: Round ended badge
  packages/grant-explorer/src/features/common/styles.ts
  packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/RoundCardStat.tsx
  packages/grant-explorer/src/features/discovery/RoundDaysLeft.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getRoundEndedText.test.tsx
Labels: 5 min review

#2524 Update ui on round edit flow in manager
  packages/common/src/index.ts
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
Labels: missing-tests, 5 min review

#2558 Explorer: [2490] Add categories
  packages/grant-explorer/src/features/categories/CategoriesGrid.tsx
  packages/grant-explorer/src/features/categories/CategoryCard.tsx
  packages/grant-explorer/src/features/categories/hooks/useCategories.ts
  packages/grant-explorer/src/features/common/styles.ts
  packages/grant-explorer/src/features/discovery/CardBanner.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
Labels: 5 min review

#2546 Explore projects page
  packages/builder/.env.example
  packages/common/package.json
  packages/common/src/config.ts
  packages/common/src/grantsStackDataClientContext.tsx
  packages/common/src/ipfs.ts
  packages/common/src/routes/explorer.ts
  packages/grant-explorer/.env.example
  packages/grant-explorer/src/features/common/ProjectBanner.tsx
  packages/grant-explorer/src/features/common/ProjectCard.test.tsx
  packages/grant-explorer/src/features/common/ProjectCard.tsx
  packages/grant-explorer/src/features/common/Spinner.tsx
  packages/grant-explorer/src/features/common/__tests__/ProjectBanner.test.tsx
  packages/grant-explorer/src/features/common/styles.ts
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
  packages/grant-explorer/src/features/discovery/PaginatedProjectsList.test.tsx
  packages/grant-explorer/src/features/discovery/PaginatedProjectsList.tsx
  packages/grant-explorer/src/features/discovery/hooks/useApplications.ts
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/index.tsx
  packages/grant-explorer/src/setupTests.ts
  packages/grant-explorer/src/store.ts
  packages/round-manager/.env.example
  pnpm-lock.yaml
Labels: 10 min review

#2557 Explorer: [2493] Add collections
  packages/grant-explorer/src/features/categories/CategoryCard.tsx
  packages/grant-explorer/src/features/collections/CollectionCard.tsx
  packages/grant-explorer/src/features/collections/CollectionsGrid.tsx
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
  packages/grant-explorer/src/features/common/styles.ts
  packages/grant-explorer/src/features/discovery/CardBanner.tsx
  packages/grant-explorer/src/features/discovery/CollectionCard.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/RoundsGrid.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
Labels: 5 min review

#2551 Explorer: 2550 filter bugs
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
  packages/grant-explorer/src/features/discovery/FilterDropdown.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/RoundCardStat.tsx
  packages/grant-explorer/src/features/discovery/RoundDaysDetails.tsx
  packages/grant-explorer/src/features/discovery/RoundDaysLeft.tsx
  packages/grant-explorer/src/features/discovery/RoundMatchAmountBadge.tsx
  packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx
  packages/grant-explorer/src/features/discovery/RoundTimeBadge.tsx
  packages/grant-explorer/src/features/discovery/RoundsFilter.tsx
  packages/grant-explorer/src/features/discovery/RoundsGrid.tsx
  packages/grant-explorer/src/features/discovery/hooks/__tests__/useFilterRounds.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts
  packages/grant-explorer/src/features/discovery/utils/__tests__/createRoundsStatusFilter.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getExplorerPageTitle.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getRoundDaysText.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getRoundEndedText.test.tsx
  packages/grant-explorer/src/features/discovery/utils/createRoundLoadingData.ts
  packages/grant-explorer/src/features/discovery/utils/createRoundsStatusFilter.ts
  packages/grant-explorer/src/features/discovery/utils/getExplorerPageTitle.ts
  packages/grant-explorer/src/test-utils.tsx
Labels: 20 min review

#2564 add new issue form
  .github/ISSUE_TEMPLATE/bug.md
  .github/ISSUE_TEMPLATE/bug_report.yml
Labels: missing-tests, 5 min review

#2567 don't lower case LIT chain names
  packages/round-manager/docs/EncryptingPII.md
  packages/round-manager/src/features/api/exports.ts
  packages/round-manager/src/features/api/lit.ts
  packages/round-manager/src/features/round/ApplicationsToApproveReject.tsx
  packages/round-manager/src/features/round/ApplicationsToReview.tsx
  packages/round-manager/src/features/round/ViewApplicationPage.tsx
  packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
Labels: missing-tests, 5 min review

#2552 Add WalletConnect v2 support to Builder
  packages/builder/.jest/setEnvVars.js
  packages/builder/src/actions/projects.ts
  packages/builder/src/utils/chains.ts
  packages/builder/src/utils/wagmi.ts
Labels: missing-tests, 5 min review

#2574 Explorer: [2556] Some application links not loading
  packages/grant-explorer/src/features/api/round.ts
Labels: 1 min review, missing-tests

#2576 feat: add pgn bridge to explorer navbar
  packages/grant-explorer/src/features/common/Navbar.tsx
Labels: missing-tests, 5 min review

#2571 Explorer: [2568] Remove redirect to grants.gitcoin.co
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
Labels: 1 min review, missing-tests

#2572 Explorer: [2569] Hide test and spam rounds
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/vitest.config.ts
Labels: missing-tests, 5 min review

#2566 Create link to report cards when donation period starts (QF rounds only)
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Labels: missing-tests, 5 min review

#2578 feat: order contributions by date desc in profile + ens support
  packages/grant-explorer/package.json
  packages/grant-explorer/src/features/api/round.ts
  packages/grant-explorer/src/features/contributors/DonationsTable.tsx
  packages/grant-explorer/src/features/contributors/TransactionButton.tsx
  packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
  packages/grant-explorer/src/features/contributors/__tests__/ViewContributionHistory.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/__tests__/useFilterRounds.test.tsx
  packages/grant-explorer/src/index.tsx
  pnpm-lock.yaml
Labels: 10 min review

#2554 Feat/grant explorer gap
  packages/grant-explorer/src/assets/icons/alert-message-white.svg
  packages/grant-explorer/src/assets/icons/milestone-flag.svg
  packages/grant-explorer/src/features/api/__tests__/utils.test.tsx
  packages/grant-explorer/src/features/api/gap.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/common/ExpandableGrid.tsx
  packages/grant-explorer/src/features/round/KarmaGrant/CompletionBadge.tsx
  packages/grant-explorer/src/features/round/KarmaGrant/GrantItem.tsx
  packages/grant-explorer/src/features/round/KarmaGrant/GrantList.tsx
  packages/grant-explorer/src/features/round/KarmaGrant/MilestoneBadge.tsx
  packages/grant-explorer/src/features/round/KarmaGrant/MilestoneItem.tsx
  packages/grant-explorer/src/features/round/KarmaGrant/MilestoneList.tsx
  packages/grant-explorer/src/features/round/KarmaGrant/MilestoneUpdate.tsx
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Labels: 10 min review

#2560 Explore project page search
  package.json
  packages/grant-explorer/.env.example
  packages/grant-explorer/src/features/categories/CategoryCard.tsx
  packages/grant-explorer/src/features/categories/hooks/useCategories.ts
  packages/grant-explorer/src/features/collections/CollectionDetails.tsx
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
  packages/grant-explorer/src/features/common/ProjectCard.test.tsx
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/PaginatedProjectsList.test.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/useApplications.ts
  packages/grant-explorer/src/index.tsx
  pnpm-lock.yaml
Labels: 10 min review

#2582 Import Grants Stack Data Client
  .github/workflows/grants-stack-data-client.yml
  .gitignore
  lefthook.yml
  package.json
  packages/common/package.json
  packages/grants-stack-data-client/.eslintrc.json
  packages/grants-stack-data-client/.prettierrc.json
  packages/grants-stack-data-client/README.md
  packages/grants-stack-data-client/openapitools.json
  packages/grants-stack-data-client/package.json
  packages/grants-stack-data-client/src/grants-stack-data-client.ts
  packages/grants-stack-data-client/src/grants-stack-data-client.types.ts
  packages/grants-stack-data-client/src/grasts-stack-data-client.test.ts
  packages/grants-stack-data-client/src/index.ts
  packages/grants-stack-data-client/src/openapi-search-client/.openapi-generator-ignore
  packages/grants-stack-data-client/src/openapi-search-client/.openapi-generator/FILES
  packages/grants-stack-data-client/src/openapi-search-client/.openapi-generator/VERSION
  packages/grants-stack-data-client/src/openapi-search-client/apis/DefaultApi.ts
  packages/grants-stack-data-client/src/openapi-search-client/apis/index.ts
  packages/grants-stack-data-client/src/openapi-search-client/index.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/ApplicationResponse.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/ApplicationSummary.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/ApplicationsResponse.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/HTTPValidationError.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/SearchResponse.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/SearchResult.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/SearchResultMeta.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/SearchType.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/ValidationError.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/ValidationErrorLocInner.ts
  packages/grants-stack-data-client/src/openapi-search-client/models/index.ts
  packages/grants-stack-data-client/src/openapi-search-client/runtime.ts
  packages/grants-stack-data-client/tsconfig.json
  pnpm-lock.yaml
  pnpm-workspace.yaml
Labels: 20 min review

#2579 experimental posthog support
  packages/grant-explorer/.env.example
  packages/grant-explorer/package.json
  packages/grant-explorer/src/index.tsx
  packages/grant-explorer/src/posthog.ts
  pnpm-lock.yaml
Labels: 1 min review, missing-tests

#2587 Project page filters
  packages/grant-explorer/src/features/common/Dropdown.tsx
  packages/grant-explorer/src/features/common/FilterDropdown.test.tsx
  packages/grant-explorer/src/features/common/FilterDropdown.tsx
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
  packages/grant-explorer/src/features/discovery/hooks/useApplications.ts
  packages/grants-stack-data-client/src/grants-stack-data-client.ts
  packages/grants-stack-data-client/src/grants-stack-data-client.types.ts
  packages/grants-stack-data-client/src/grasts-stack-data-client.test.ts
Labels: 5 min review

#2591 Explorer: Show 4 categories
  packages/grant-explorer/src/assets/categories/category_01.jpg
  packages/grant-explorer/src/assets/categories/category_02.jpg
  packages/grant-explorer/src/assets/categories/category_03.jpg
  packages/grant-explorer/src/assets/categories/category_04.jpg
  packages/grant-explorer/src/assets/categories/category_05.jpg
  packages/grant-explorer/src/assets/categories/category_06.jpg
  packages/grant-explorer/src/assets/categories/category_07.jpg
  packages/grant-explorer/src/assets/categories/category_08.jpg
  packages/grant-explorer/src/assets/categories/category_09.jpg
  packages/grant-explorer/src/assets/categories/category_10.jpg
  packages/grant-explorer/src/assets/categories/category_11.jpg
  packages/grant-explorer/src/assets/categories/category_12.jpg
  packages/grant-explorer/src/assets/categories/category_13.jpg
  packages/grant-explorer/src/assets/categories/category_14.jpg
  packages/grant-explorer/src/assets/categories/category_15.jpg
  packages/grant-explorer/src/assets/categories/category_16.jpg
  packages/grant-explorer/src/features/categories/CategoryCard.tsx
  packages/grant-explorer/src/features/categories/hooks/useCategories.ts
  packages/grant-explorer/src/features/discovery/CardBanner.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
Labels: 1 min review, missing-tests

#2594 Fix Duplicate Cart Items in Explorer
  packages/grant-explorer/src/cartStore.test.tsx
  packages/grant-explorer/src/store.ts
Labels: 5 min review

#2599 Revert "Fix Duplicate Cart Items in Explorer"
  packages/grant-explorer/src/cartStore.test.tsx
  packages/grant-explorer/src/store.ts
Labels: 1 min review

#2601 Fix Duplicate Cart Items in Explorer
  packages/grant-explorer/src/cartStore.test.tsx
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
  packages/grant-explorer/src/store.ts
Labels: 5 min review

#2592 Feat/collections
  packages/grant-explorer/src/assets/collections/collection_01.jpg
  packages/grant-explorer/src/assets/collections/collection_02.jpg
  packages/grant-explorer/src/assets/collections/collection_03.jpg
  packages/grant-explorer/src/assets/collections/collection_04.jpg
  packages/grant-explorer/src/assets/collections/collection_05.jpg
  packages/grant-explorer/src/assets/collections/collection_06.jpg
  packages/grant-explorer/src/assets/collections/collection_07.jpg
  packages/grant-explorer/src/assets/collections/collection_08.jpg
  packages/grant-explorer/src/features/collections/CollectionCard.tsx
  packages/grant-explorer/src/features/collections/CollectionDetails.tsx
  packages/grant-explorer/src/features/collections/CollectionsGrid.tsx
  packages/grant-explorer/src/features/collections/data/firstTimeGrantees.ts
  packages/grant-explorer/src/features/collections/data/veterans.ts
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
  packages/grant-explorer/src/features/discovery/CardBanner.tsx
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/useApplications.ts
  pnpm-lock.yaml
Labels: 10 min review

#2573 Explorer: [2559] Mobile navbar
  packages/grant-explorer/src/assets/explorer-logo-mobile.svg
  packages/grant-explorer/src/features/common/Navbar.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
Labels: missing-tests, 5 min review

#2611 explorer: show spinner in application page while loading
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Labels: 1 min review, missing-tests

#2593 revert turbo invocation in lefthook
  lefthook.yml
Labels: 1 min review, missing-tests

#2607 Explorer: [2606] Fix link to explore rounds in navbar
  packages/grant-explorer/src/features/common/Navbar.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
Labels: 1 min review, missing-tests

#2616 Explorer: Use toLowerCase for addresses - fixes tests
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
Labels: 1 min review

#2622 Use checksum addresses for application refs
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
Labels: 1 min review, missing-tests

#2613 Randomize collections & reduce amount of unnecessary requests
  packages/grant-explorer/src/features/discovery/hooks/useApplications.ts
Labels: 1 min review, missing-tests

#2614 Add partial empty state for project search
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
Labels: 1 min review, missing-tests

#2619 Hide additional test rounds on explorer
  packages/grant-explorer/src/features/api/rounds.ts
Labels: 1 min review, missing-tests

#2617 fix: avoid recursive pnpm test; don't let turbo take all cpus
  lefthook.yml
  package.json
Labels: 1 min review, missing-tests

#2623 Fix Collection Title Casing
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
Labels: 1 min review, missing-tests

#2630 fix: do not revalidate matching estimates
  packages/grant-explorer/src/hooks/matchingEstimate.ts
Labels: 1 min review, missing-tests

#2629 fix unable to edit application end date bug
  packages/round-manager/src/context/round/UpdateRoundContext.tsx
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
Labels: 1 min review, missing-tests

#2635 Explorer: [2634] Mobile UI issues collections
  packages/grant-explorer/src/features/collections/CollectionsGrid.tsx
  packages/grant-explorer/src/features/discovery/RoundsGrid.tsx
Labels: 1 min review, missing-tests

#2633 Explorer: [2624] Add Live GG19 stats button
  packages/grant-explorer/src/features/collections/CollectionDetails.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/LandingSection.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
Labels: 5 min review

#2618 Update post-checkout Twitter share message copy
  packages/grant-explorer/src/features/round/ThankYou.test.tsx
  packages/grant-explorer/src/features/round/ThankYou.tsx
Labels: 1 min review

#2631 Explorer: [2620] Add collections
  packages/grant-explorer/src/assets/collections/collection_33.jpg
  packages/grant-explorer/src/assets/collections/collection_34.jpg
  packages/grant-explorer/src/assets/collections/collection_35.jpg
  packages/grant-explorer/src/assets/collections/collection_36.jpg
  packages/grant-explorer/src/features/collections/CollectionsGrid.tsx
  packages/grant-explorer/src/features/collections/data/carlsCollection.ts
  packages/grant-explorer/src/features/collections/data/midnightGospel.ts
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
Labels: missing-tests, 5 min review

#2639 Explorer: [2596] Fix incorrect projects in explore rounds page
  packages/grant-explorer/src/features/api/rounds.ts
Labels: 1 min review, missing-tests

#2640 fix: live stats link
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
Labels: 1 min review

#2647 Explorer: [2641] Add MxWeb3 Collection
  packages/grant-explorer/src/features/collections/CollectionsGrid.tsx
  packages/grant-explorer/src/features/collections/data/mxWeb3.ts
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
Labels: missing-tests, 5 min review

#2650 Explorer: remove unused use of query string in Karma tab
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
Labels: 1 min review, missing-tests

#2653 Update carlsCollection.ts
  packages/grant-explorer/src/features/collections/data/carlsCollection.ts
Labels: 1 min review, missing-tests

#2656 feat: don't display matching estimates for polygon
  packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  packages/grant-explorer/src/hooks/matchingEstimate.ts
Labels: 1 min review, missing-tests

#2649 update polygonscan tx explorer link
  packages/grant-explorer/src/features/api/utils.ts
Labels: 1 min review, missing-tests

#2648 fix partial empty state msg issue on categories
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
Labels: 1 min review, missing-tests

#2659 truncate project summary in round page cards
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Labels: 1 min review, missing-tests

#2658 feat: re-enable matching estimates for polygon
  packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx
  packages/grant-explorer/src/hooks/matchingEstimate.ts
Labels: 1 min review, missing-tests

#2672 Add collections
  packages/grant-explorer/src/features/collections/data/givethGalaxy.ts
  packages/grant-explorer/src/features/collections/data/griffsOSS.ts
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
Labels: missing-tests, 5 min review

#2674 Explorer: 2668 update collections layout + shuffle
  packages/grant-explorer/src/features/collections/CollectionsGrid.tsx
  packages/grant-explorer/src/features/collections/hooks/useCollections.ts
Labels: 1 min review, missing-tests

#2677 update PGN Bridge link to point to docs
  packages/grant-explorer/src/features/common/Navbar.tsx
Labels: 1 min review, missing-tests

#2682 enable add all projects to cart button in collections
  packages/grant-explorer/src/features/collections/CollectionDetails.tsx
Labels: 1 min review, missing-tests

#2685 temporarily disable matching estimate
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
Labels: 1 min review, missing-tests

#2686 add disableEstimate var
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
Labels: 1 min review, missing-tests

#2688 disable all matching estimate
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  packages/grant-explorer/src/hooks/matchingEstimate.ts
Labels: missing-tests, 5 min review

#2690 disable matching estimate via env var
  packages/common/src/config.ts
  packages/grant-explorer/.env.example
  packages/grant-explorer/src/hooks/matchingEstimate.ts
Labels: 1 min review, missing-tests

#2700 Add copy to donation history page
  packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
Labels: 1 min review, missing-tests

#2699 Explorer: [2695] Add number of projects for add collection to cart
  packages/grant-explorer/src/features/collections/CollectionDetails.tsx
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
Labels: 1 min review, missing-tests

#2706 update twitter share url with the new path
  packages/grant-explorer/src/features/round/ThankYou.test.tsx
  packages/grant-explorer/src/features/round/ThankYou.tsx
Labels: 1 min review
