Repository gitcoinco/grants-stack, pull requests merged in 2024-02, with the labels that each got.

#2807 Data layer v2 - Profiles
  packages/builder/.env.example
  packages/builder/package.json
  packages/builder/src/__tests__/components/base/Alert.test.tsx
  packages/builder/src/__tests__/components/grants/List.test.tsx
  packages/builder/src/__tests__/components/grants/Show.test.tsx
  packages/builder/src/actions/grantsMetadata.ts
  packages/builder/src/actions/newGrant.ts
  packages/builder/src/actions/projects.ts
  packages/builder/src/actions/rounds.ts
  packages/builder/src/components/AlloWrapper.tsx
  packages/builder/src/components/grants/Card.tsx
  packages/builder/src/components/grants/Edit.tsx
  packages/builder/src/components/grants/List.tsx
  packages/builder/src/components/grants/Show.tsx
  packages/builder/src/components/rounds/Show.tsx
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/index.tsx
  packages/builder/src/reducers/projects.ts
  packages/builder/src/types/index.ts
  packages/builder/src/utils/chains.ts
  packages/builder/src/utils/roundApplication.ts
  packages/builder/src/utils/test_utils.tsx
  packages/builder/src/utils/utils.ts
  packages/builder/src/utils/wallet.ts
  packages/common/.env.test
  packages/common/package.json
  packages/common/src/allo/allo.ts
  packages/common/src/allo/backends/allo-v1.ts
  packages/common/src/allo/backends/allo-v2.test.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/common/src/allo/backends/test-utils.ts
  packages/common/src/allo/indexer.ts
  packages/common/src/allo/transaction-sender.ts
  packages/common/src/chains.ts
  packages/common/src/components/Footer.tsx
  packages/common/src/config.ts
  packages/common/src/index.ts
  packages/data-layer/package.json
  packages/data-layer/src/data-layer.test.ts
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data-layer.types.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/data-layer/src/react.tsx
  packages/grant-explorer/src/index.tsx
  pnpm-lock.yaml
Labels: Feature Branch, 20 min review

#2869 temporary fix: active rounds sorting
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/hooks/__tests__/useFilterRounds.test.tsx
Labels: 1 min review

#2886 explorer: enable markdown for any type of answer in round applications
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/index.css
Labels: missing-tests, 5 min review

#2893 data-layer: filter out spam rounds based on a temporary csv blacklist
  packages/data-layer/src/backends/legacy.ts
Labels: missing-tests, 5 min review

#2860 Indexer builder applications
  packages/builder/src/__tests__/components/application/Form.test.tsx
  packages/builder/src/__tests__/components/grants/List.test.tsx
  packages/builder/src/__tests__/components/providers/Github.test.tsx
  packages/builder/src/__tests__/components/rounds/Show.test.tsx
  packages/builder/src/__tests__/reducers/projects.test.ts
  packages/builder/src/__tests__/utils/RoundApplicationBuilder.test.ts
  packages/builder/src/actions/projects.ts
  packages/builder/src/actions/roundApplication.ts
  packages/builder/src/actions/rounds.ts
  packages/builder/src/components/application/AboutProject.tsx
  packages/builder/src/components/application/Form.tsx
  packages/builder/src/components/application/FullPreview.tsx
  packages/builder/src/components/base/__tests__/formValidation.test.ts
  packages/builder/src/components/base/formValidation.ts
  packages/builder/src/components/grants/About.tsx
  packages/builder/src/components/grants/ApplicationCard.tsx
  packages/builder/src/components/grants/Details.tsx
  packages/builder/src/components/grants/List.tsx
  packages/builder/src/components/grants/Show.tsx
  packages/builder/src/components/grants/rounds/LinkManager.tsx
  packages/builder/src/components/grants/rounds/RoundListItem.tsx
  packages/builder/src/components/grants/rounds/Rounds.tsx
  packages/builder/src/components/grants/rounds/__tests__/Rounds.test.tsx
  packages/builder/src/components/grants/stats/Stats.tsx
  packages/builder/src/components/providers/Github.tsx
  packages/builder/src/components/providers/Twitter.tsx
  packages/builder/src/components/rounds/Apply.tsx
  packages/builder/src/components/rounds/Show.tsx
  packages/builder/src/components/rounds/ViewApplication.tsx
  packages/builder/src/hooks/useValidateCredential.tsx
  packages/builder/src/index.tsx
  packages/builder/src/reducers/projects.ts
  packages/builder/src/types/index.ts
  packages/builder/src/utils/RoundApplicationBuilder.ts
  packages/builder/src/utils/components.ts
  packages/builder/src/utils/roundApplication.ts
  packages/builder/src/utils/test_utils.tsx
  packages/builder/src/utils/utils.ts
  packages/data-layer/src/backends/legacy.ts
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/index.ts
  packages/data-layer/src/queries.ts
  packages/data-layer/src/roundApplication.types.ts
  pnpm-lock.yaml
Labels: 20 min review, v1 -> v2

#2894 Add usdglo as payout token
  packages/common/src/chain-ids.ts
  packages/common/src/payoutTokens.ts
  packages/round-manager/public/logos/usdglo-logo.svg
  packages/round-manager/src/features/api/payoutTokens.ts
Labels: missing-tests, 5 min review

#2895 add allo version switch button to the footer
  packages/builder/tailwind.config.js
  packages/common/src/components/Footer.tsx
  packages/common/src/config.ts
  packages/grant-explorer/src/features/common/DefaultLayout.tsx
Labels: missing-tests, 5 min review

#2859 feat: add synpress
  docs/DEV.md
  package.json
  packages/builder/.eslintrc.js
  packages/builder/craco.config.js
  packages/builder/e2e/homepage.test.ts
  packages/builder/fixtures.ts
  packages/builder/package.json
  packages/builder/playwright.config.js
  packages/builder/tsconfig.json
  packages/grant-explorer/e2e/homepage.test.ts
  packages/grant-explorer/fixtures.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/playwright.config.js
  packages/grant-explorer/vitest.config.ts
  packages/round-manager/.gitignore
  packages/round-manager/e2e/createDgRound.test.ts
  packages/round-manager/e2e/createProgram.test.ts
  packages/round-manager/e2e/homepage.test.ts
  packages/round-manager/fixtures.ts
  packages/round-manager/package.json
  packages/round-manager/playwright.config.js
  pnpm-lock.yaml
Labels: 30 min review

#2908 fix: default to mainnet if chain id is not supported
  packages/builder/src/utils/AlloWrapper.tsx
Labels: 1 min review, missing-tests

#2904 add applyToRound to allo.ts and wire it into builder for v1
  packages/builder/src/actions/roundApplication.ts
  packages/builder/src/components/rounds/Apply.tsx
  packages/builder/src/components/rounds/ViewApplication.tsx
  packages/builder/src/utils/AlloWrapper.tsx
  packages/builder/src/utils/components.ts
  packages/common/package.json
  packages/common/src/allo/allo.ts
  packages/common/src/allo/backends/allo-v1.test.ts
  packages/common/src/allo/backends/allo-v1.ts
  packages/common/src/allo/backends/allo-v2.test.ts
  packages/common/src/allo/backends/allo-v2.ts
  pnpm-lock.yaml
Labels: 20 min review, v1 -> v2

#2868 Performance
  .gitignore
  package.json
  packages/builder/package.json
  packages/builder/rsbuild.config.ts
  packages/builder/tsconfig.json
  packages/common/package.json
  packages/common/tsconfig.json
  packages/data-layer/package.json
  packages/data-layer/tsconfig.json
  packages/grant-explorer/package.json
  packages/grant-explorer/rsbuild.config.ts
  packages/grant-explorer/tsconfig.json
  packages/round-manager/package.json
  packages/round-manager/rsbuild.config.ts
  packages/round-manager/tsconfig.json
  pnpm-lock.yaml
Labels: missing-tests, 30 min review

#2712 Explorer: [2670] Application page indexer data
  packages/common/src/index.ts
  packages/grant-explorer/src/features/projects/hooks/__tests__/data/application.ts
  packages/grant-explorer/src/features/projects/hooks/__tests__/useApplication.test.tsx
  packages/grant-explorer/src/features/projects/hooks/useApplication.ts
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
Labels: 5 min review

#2926 v2: builder applyToRound
  packages/builder/.gitignore
  packages/builder/package.json
  packages/builder/src/__tests__/components/application/Form.test.tsx
  packages/builder/src/actions/grantsMetadata.ts
  packages/builder/src/actions/projects.ts
  packages/builder/src/actions/roundApplication.ts
  packages/builder/src/actions/rounds.ts
  packages/builder/src/components/application/Form.tsx
  packages/builder/src/components/application/FullPreview.tsx
  packages/builder/src/components/grants/ApplicationCard.tsx
  packages/builder/src/components/grants/rounds/RoundListItem.tsx
  packages/builder/src/components/rounds/Apply.tsx
  packages/builder/src/components/rounds/Show.tsx
  packages/builder/src/components/rounds/ViewApplication.tsx
  packages/builder/src/reducers/projects.ts
  packages/builder/src/reducers/rounds.ts
  packages/builder/src/types/index.ts
  packages/builder/src/utils/components.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/common/src/allo/roundIdentifier.ts
  packages/common/src/index.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  pnpm-lock.yaml
Labels: 20 min review

#2923 Local dev env setup
  docker-compose.yml
  packages/common/src/chains.ts
  scripts/README.md
  scripts/dev
Labels: missing-tests, 5 min review

#2939 remove hardcoded strategy name from application.round
  packages/common/src/index.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/discovery/FilterDropdown.tsx
  packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx
  packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts
  packages/grant-explorer/src/features/discovery/utils/__tests__/getExplorerPageTitle.test.tsx
  packages/grant-explorer/src/features/discovery/utils/getExplorerPageTitle.ts
  packages/grant-explorer/src/features/projects/hooks/useApplication.ts
  packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
Labels: 5 min review

#2871 fetch Allo V2 programs from the indexer
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/queries.ts
Labels: missing-tests, 5 min review

#2946 Load Programs from Indexer
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/round-manager/src/context/program/ReadProgramContext.tsx
  packages/round-manager/src/features/api/__tests__/program.test.ts
  packages/round-manager/src/features/api/program.ts
  packages/round-manager/src/features/program/CreateProgramPage.tsx
  packages/round-manager/src/features/round/__tests__/CreateRoundPage.test.tsx
Labels: 5 min review

#2949 Updated Round Types - Builder, Common, Data-Layer
  packages/builder/src/actions/rounds.ts
  packages/builder/src/components/grants/ApplicationCard.tsx
  packages/builder/src/components/grants/rounds/RoundListItem.tsx
  packages/builder/src/components/grants/stats/Stats.tsx
  packages/common/src/allo/roundIdentifier.ts
  packages/common/src/index.ts
  packages/data-layer/src/queries.ts
Labels: missing-tests, 5 min review

#2947 Add sepolia in manager & explorer
  packages/builder/.env.example
  packages/builder/.env.test
  packages/builder/src/utils/chains.ts
  packages/common/.env.test
  packages/common/src/allo/addresses/allo-v1.ts
  packages/common/src/chain-ids.ts
  packages/common/src/config.ts
  packages/common/src/graphql_fetch.ts
  packages/common/src/payoutTokens.ts
  packages/grant-explorer/.env.example
  packages/grant-explorer/.env.test
  packages/grant-explorer/src/app/chainConfig.ts
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/.env.example
  packages/round-manager/.env.test
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/payoutTokens.ts
  packages/round-manager/src/features/api/utils.ts
Labels: missing-tests, 5 min review

#2954 fix direct round view
  packages/round-manager/src/features/common/Utils.ts
  packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx
  packages/round-manager/src/features/round/ViewApplicationPage.tsx
  packages/round-manager/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/round/__tests__/ApplicationDirectPayout.test.tsx
  packages/round-manager/src/features/round/__tests__/ApplicationsToReview.test.tsx
  packages/round-manager/src/features/round/__tests__/ViewApplicationPage.test.tsx
  packages/round-manager/src/test-utils.tsx
Labels: 1 min review

#2952 filter out duplicate bot rounds
  packages/data-layer/src/data-layer.test.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/round-manager/src/features/api/__tests__/program.test.ts
  packages/round-manager/src/features/api/program.ts
  packages/round-manager/src/features/api/round.ts
  packages/round-manager/src/features/api/types.ts
Labels: 5 min review

#2862 Add support for scroll mainnet
  packages/builder/.env.example
  packages/builder/.env.test
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/utils/chains.ts
  packages/builder/src/utils/wallet.ts
  packages/common/.env.test
  packages/common/src/allo/addresses/allo-v1.ts
  packages/common/src/chain-ids.ts
  packages/common/src/chains.ts
  packages/common/src/config.ts
  packages/common/src/graphql_fetch.ts
  packages/common/src/icons/scroll-logo.svg
  packages/common/src/index.ts
  packages/common/src/payoutTokens.ts
  packages/data-layer/src/data-layer.test.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/grant-explorer/.env.example
  packages/grant-explorer/.env.test
  packages/grant-explorer/public/logos/scroll-logo.svg
  packages/grant-explorer/src/app/chainConfig.ts
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/.env.example
  packages/round-manager/.env.test
  packages/round-manager/package.json
  packages/round-manager/public/logos/scroll-logo.svg
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/features/api/__tests__/program.test.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/deployments.ts
  packages/round-manager/src/features/api/payoutTokens.ts
  packages/round-manager/src/features/api/program.ts
  packages/round-manager/src/features/api/round.ts
  packages/round-manager/src/features/api/types.ts
  packages/round-manager/src/features/api/utils.ts
  pnpm-lock.yaml
Labels: missing-tests, 30 min review

#2934 Create Allo v2 Round
  packages/common/.env.test
  packages/common/package.json
  packages/common/src/allo/allo.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/common/src/allo/common.ts
  packages/common/src/allo/indexer.ts
  packages/common/src/allo/transaction-sender.ts
  packages/common/src/config.ts
  packages/common/src/index.ts
  packages/grant-explorer/.env.test
  packages/round-manager/.env.example
  packages/round-manager/.env.test
  packages/round-manager/src/features/api/round.ts
  packages/round-manager/src/features/common/Utils.ts
  packages/round-manager/src/features/round/RoundApplicationForm.tsx
  packages/round-manager/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/stores/createRoundStore.ts
  pnpm-lock.yaml
Labels: missing-tests, 10 min review

#2944 add start to dev commands to run `concurrently` for all the packages
  package.json
  packages/builder/src/index.tsx
  packages/common/package.json
  packages/data-layer/package.json
  pnpm-lock.yaml
  scripts/README.md
  scripts/dev
Labels: missing-tests, 10 min review

#2916 Fetch landing page and explore rounds from indexer
  .gitignore
  package.json
  packages/common/src/chains.ts
  packages/common/src/index.ts
  packages/data-layer/src/backends/legacy.test.ts
  packages/data-layer/src/backends/legacy.ts
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/grant-explorer/src/features/api/__tests__/round.test.tsx
  packages/grant-explorer/src/features/api/contracts.ts
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/discovery/ActiveRoundSection.tsx
  packages/grant-explorer/src/features/discovery/FilterDropdown.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
  packages/grant-explorer/src/features/discovery/RoundCard.tsx
  packages/grant-explorer/src/features/discovery/RoundDaysDetails.tsx
  packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx
  packages/grant-explorer/src/features/discovery/RoundsGrid.tsx
  packages/grant-explorer/src/features/discovery/SortDropdown.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/__tests__/useFilterRounds.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/useFilterRounds.ts
  packages/grant-explorer/src/features/discovery/utils/__tests__/createRoundsStatusFilter.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getExplorerPageTitle.test.tsx
  packages/grant-explorer/src/features/discovery/utils/__tests__/getFilterLabel.test.tsx
  packages/grant-explorer/src/features/discovery/utils/createRoundLoadingData.ts
  packages/grant-explorer/src/features/discovery/utils/createRoundsStatusFilter.ts
  packages/grant-explorer/src/features/discovery/utils/getSortLabel.ts
  packages/grant-explorer/src/test-utils.tsx
  pnpm-lock.yaml
Labels: 20 min review

#3034 Apply to Direct Round ON MUMBAI
  packages/builder/src/__tests__/components/application/Form.test.tsx
  packages/builder/src/__tests__/reducers/projects.test.ts
  packages/builder/src/actions/projects.ts
  packages/builder/src/actions/roundApplication.ts
  packages/builder/src/actions/rounds.ts
  packages/builder/src/components/application/Form.tsx
  packages/builder/src/components/grants/ApplicationCard.tsx
  packages/builder/src/components/grants/rounds/RoundListItem.tsx
  packages/builder/src/components/grants/stats/Stats.tsx
  packages/builder/src/components/rounds/Apply.tsx
  packages/builder/src/components/rounds/Show.tsx
  packages/builder/src/components/rounds/ViewApplication.tsx
  packages/builder/src/types/index.ts
  packages/builder/src/utils/test_utils.tsx
  packages/builder/src/utils/utils.ts
  packages/common/src/allo/allo.ts
  packages/common/src/allo/backends/allo-v2.test.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/data-layer/src/data-layer.test.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  pnpm-lock.yaml
Labels: chore
