Repository gitcoinco/grants-stack, pull requests merged in 2024-04, with the labels that each got.

#3240 3236/fix for operators list
  packages/round-manager/src/features/program/CreateProgramPage.tsx
Labels: 5 min review

#3335 chore: prevent unchecking all chains in checkout
  packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx
Labels: chore

#3312 fixes for sepolia/zksync/bump allo sdk
  packages/builder/src/contracts/deployments.ts
  packages/common/package.json
  packages/common/src/chain-ids.ts
  packages/common/src/chains.ts
  pnpm-lock.yaml
Labels: chore

#3329 3318/mrc style updates
  packages/grant-explorer/src/features/common/ConfirmationModal.tsx
  packages/grant-explorer/src/features/common/MRCProgressModal.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/ChainConfirmationModalBody.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/MRCProgressModalBody.tsx
  packages/grant-explorer/tailwind.config.js
Labels: design

#3337 Feat: round & application page design updates
  packages/common/src/components/Footer.tsx
  packages/common/src/icons.tsx
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/grant-explorer/src/assets/warpcast-logo.svg
  packages/grant-explorer/src/assets/x-logo.svg
  packages/grant-explorer/src/features/common/Breadcrumb.tsx
  packages/grant-explorer/src/features/common/DefaultLayout.tsx
  packages/grant-explorer/src/features/common/GenericModal.tsx
  packages/grant-explorer/src/features/common/Navbar.tsx
  packages/grant-explorer/src/features/common/ProjectCard.tsx
  packages/grant-explorer/src/features/common/__tests__/GenericModal.test.tsx
  packages/grant-explorer/src/features/projects/hooks/useRoundApplications.ts
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/index.css
  packages/grant-explorer/tailwind.config.js
Labels: design

#3328 WIP/3297 Add Explore Projects Tab
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
  packages/grant-explorer/src/features/discovery/LandingTabs.tsx
  packages/grant-explorer/src/features/round/CollectionShareDialog.tsx
  packages/grant-explorer/src/index.tsx
Labels: Feature Branch

#3353 add copy to contribution history page
  packages/grant-explorer/src/features/contributors/ViewContributionHistory.tsx
Labels: 1 min review

#3349 345 remove version banner
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
Labels: chore, 5 min review

#3344 Add OpenSourceObserver stats to explorer
  packages/grant-explorer/.env.example
  packages/grant-explorer/package.json
  packages/grant-explorer/src/features/api/oso.ts
  packages/grant-explorer/src/features/common/utils/utils.ts
  packages/grant-explorer/src/features/round/KarmaGrant/GrantList.tsx
  packages/grant-explorer/src/features/round/OSO/ImpactStats.tsx
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  pnpm-lock.yaml
Labels: backlog, explorer
