Repository gitcoinco/grants-stack, pull requests merged in 2024-01, with the labels that each got.

#2767 fix: only index from projectregistry contract creation block on polygon pos
  packages/builder/src/actions/projects.ts
Labels: 1 min review, missing-tests

#2772 Remove usdc as payout & donation token on zksync
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/src/features/api/payoutTokens.ts
Labels: 1 min review, missing-tests

#2773 fix: fonts and styles in passport banner and navbarˆ
  packages/grant-explorer/src/features/common/Navbar.tsx
  packages/grant-explorer/src/features/common/PassportWidget.tsx
  packages/grant-explorer/src/index.css
Labels: 1 min review, missing-tests

#2497 feat: disable finalization button when round is not fully funded
  packages/round-manager/src/features/api/payoutTokens.ts
  packages/round-manager/src/features/round/QuadraticFundingForm.tsx
  packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
  packages/round-manager/src/features/round/__tests__/ViewRoundResults.test.tsx
Labels: 5 min review

#2776 fix: website input glitch
  packages/builder/src/components/base/ProjectForm.tsx
  packages/builder/src/components/grants/inputs.tsx
Labels: 1 min review, missing-tests

#2795 fix: if no passport rounds in cart, act as if passport is valid
  packages/grant-explorer/src/features/common/MatchingEstimateTooltip.tsx
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
Labels: 1 min review, missing-tests

#2794 fix round loading error on builder
  packages/builder/src/actions/rounds.ts
Labels: 1 min review, missing-tests

#2763 Fix payouts for individual projects
  packages/round-manager/src/features/api/payoutStrategy/payoutStrategy.ts
  packages/round-manager/src/features/round/ViewFundGrantees.tsx
  packages/round-manager/src/features/round/__tests__/ViewFundGrantees.test.tsx
Labels: 1 min review

#2796 Common Allo interface for V1 and V2
  packages/common/package.json
  packages/common/src/allo/abis/allo-v1/DirectPayoutStrategyFactory.ts
  packages/common/src/allo/abis/allo-v1/DirectPayoutStrategyImplementation.ts
  packages/common/src/allo/abis/allo-v1/ProjectRegistry.ts
  packages/common/src/allo/abis/allo-v1/QuadraticFundingVotingStrategyFactory.ts
  packages/common/src/allo/abis/allo-v1/QuadraticFundingVotingStrategyImplementation.ts
  packages/common/src/allo/abis/allo-v1/RoundFactory.ts
  packages/common/src/allo/abis/allo-v1/RoundImplementation.ts
  packages/common/src/allo/allo.ts
  packages/common/src/allo/backends/allo-v1.test.ts
  packages/common/src/allo/backends/allo-v1.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/common/src/allo/common.ts
  packages/common/src/allo/indexer.ts
  packages/common/src/allo/ipfs.ts
  packages/common/src/allo/operation.ts
  packages/common/src/allo/react.tsx
  packages/common/src/allo/transaction-sender.ts
  packages/data-layer/src/data-layer.test.ts
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data-layer.types.ts
  packages/grant-explorer/src/context/RoundContext.tsx
  packages/grant-explorer/src/context/__tests__/RoundContext.test.tsx
  packages/grant-explorer/src/features/api/rounds.ts
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/__tests__/useFilterRounds.test.tsx
  packages/grant-explorer/src/features/discovery/hooks/useApplications.ts
  packages/grant-explorer/src/features/round/ViewCartPage/SummaryContainer.tsx
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/test-utils.tsx
  pnpm-lock.yaml
Labels: 20 min review

#2810 fix: allow jpeg files in image upload dialog in builderˆ
  packages/builder/src/components/base/ImageInput.tsx
Labels: 1 min review, missing-tests

#2809 fix: rolling applications bug on edit page
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
Labels: missing-tests, 5 min review

#2808 Implement ethers transaction sender
  packages/common/src/allo/transaction-sender.ts
Labels: missing-tests, 5 min review

#2820 Fix common, make it an actual package
  .github/workflows/common.yml
  package.json
  packages/common/package.json
  packages/common/src/chains.ts
  packages/common/tsconfig.json
  pnpm-lock.yaml
Labels: missing-tests, 5 min review

#2821 fix lit decryption issue in manager on zksync.
  packages/builder/package.json
  packages/round-manager/package.json
  pnpm-lock.yaml
Labels: missing-tests, 10 min review

#2806 Add Allo V2 SDK and Implement Project Creation with Common Interface
  packages/builder/package.json
  packages/builder/src/__tests__/components/grants/List.test.tsx
  packages/builder/src/__tests__/components/rounds/Show.test.tsx
  packages/builder/src/__tests__/reducers/projects.test.ts
  packages/builder/src/actions/newGrant.ts
  packages/builder/src/components/AlloWrapper.tsx
  packages/builder/src/components/base/Preview.tsx
  packages/builder/src/index.tsx
  packages/common/package.json
  packages/common/src/allo/abis/allo-v2/Registry.ts
  packages/common/src/allo/allo.ts
  packages/common/src/allo/backends/allo-v1.ts
  packages/common/src/allo/backends/allo-v2.test.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/common/src/allo/ipfs.ts
  packages/common/src/allo/react.tsx
  packages/common/src/allo/transaction-sender.ts
  packages/common/src/index.ts
  packages/common/tsconfig.json
  packages/round-manager/craco.config.js
  packages/round-manager/package.json
  pnpm-lock.yaml
Labels: 20 min review

#2671 Explorer: Application page redesign
  packages/grant-explorer/src/assets/github-logo.svg
  packages/grant-explorer/src/assets/icons/ethereum-icon.svg
  packages/grant-explorer/src/assets/icons/globe-icon.svg
  packages/grant-explorer/src/assets/twitter-logo.svg
  packages/grant-explorer/src/features/common/Breadcrumb.tsx
  packages/grant-explorer/src/features/common/DefaultLayout.tsx
  packages/grant-explorer/src/features/common/RoundEndedBanner.tsx
  packages/grant-explorer/src/features/common/utils/truncate.ts
  packages/grant-explorer/src/features/discovery/ExploreProjectsPage.tsx
  packages/grant-explorer/src/features/discovery/ExploreRoundsPage.tsx
  packages/grant-explorer/src/features/discovery/LandingPage.tsx
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
  packages/grant-explorer/tailwind.config.js
Labels: 10 min review

#2822 chore: add recommended libraries and mention them under development docs
  docs/DEV.md
  docs/LIBRARIES.md
Labels: 1 min review, missing-tests, safe-change

#2833 Add support for data token on polygon
  packages/common/src/index.ts
  packages/grant-explorer/public/logos/data-logo.svg
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/public/logos/data-logo.svg
  packages/round-manager/src/features/api/payoutTokens.ts
Labels: 1 min review, missing-tests

#2836 fixing registry address
  packages/common/src/allo/backends/allo-v1.ts
Labels: 1 min review, missing-tests

#2840 fix send transaction type safety
  packages/common/src/allo/backends/allo-v1.ts
  packages/common/src/allo/transaction-sender.ts
Labels: 1 min review, missing-tests

#2835 tests: unignore and fix tests
  packages/builder/src/__tests__/components/application/Form.test.tsx
  packages/grant-explorer/src/features/common/__tests__/ErrorModal.test.tsx
  packages/grant-explorer/src/features/discovery/__tests__/LandingPage.test.tsx
  packages/grant-explorer/src/features/round/ViewCartPage.ignored.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewProjectDetails.test.tsx
  packages/grant-explorer/src/features/round/__tests__/ViewRoundPage.test.tsx
  packages/grant-explorer/src/index.tsx
Labels: 1 min review
