Repository gitcoinco/grants-stack, pull requests merged in 2024-05, with the labels that each got.

#3406 update posthog with new account
  packages/grant-explorer/.env.example
  packages/grant-explorer/package.json
  packages/grant-explorer/src/features/common/ProjectCard.tsx
  packages/grant-explorer/src/features/discovery/PaginatedProjectsList.tsx
  packages/grant-explorer/src/index.tsx
  packages/grant-explorer/src/posthog.ts
  pnpm-lock.yaml
Labels: analytics

#3336 Manager changes for Passport Lite x Cluster Match MVP
  packages/common/src/index.ts
  packages/data-layer/src/data.types.ts
  packages/grant-explorer/src/features/common/PassportWidget.tsx
  packages/grant-explorer/src/features/projects/hooks/__tests__/data/application.ts
  packages/grant-explorer/src/features/round/ViewCartPage/RoundInCart.tsx
  packages/grant-explorer/src/features/round/ViewProjectDetails.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/src/test-utils.tsx
  packages/round-manager/package.json
  packages/round-manager/src/features/api/types.ts
  packages/round-manager/src/features/api/utils.ts
  packages/round-manager/src/features/round/QuadraticFundingForm.tsx
  packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
  packages/round-manager/src/test-utils.tsx
  pnpm-lock.yaml
Labels: Feature Branch

#3341 Add direct grants lite
  package.json
  packages/builder/src/actions/rounds.ts
  packages/builder/src/components/Header.tsx
  packages/builder/src/components/application/AboutProject.tsx
  packages/builder/src/components/base/Toast.tsx
  packages/builder/src/components/rounds/Show.tsx
  packages/builder/src/utils/components.ts
  packages/common/.env.test
  packages/common/package.json
  packages/common/src/allo/allo.ts
  packages/common/src/allo/application.ts
  packages/common/src/allo/backends/allo-v1.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/common/src/allo/common.ts
  packages/common/src/allo/transaction-sender.ts
  packages/common/src/index.ts
  packages/common/src/types.ts
  packages/common/tsconfig.json
  packages/data-layer/src/data-layer.test.ts
  packages/data-layer/src/data-layer.ts
  packages/data-layer/src/data.types.ts
  packages/data-layer/src/queries.ts
  packages/data-layer/src/utils.ts
  packages/grant-explorer/package.json
  packages/grant-explorer/src/features/api/utils.ts
  packages/grant-explorer/src/features/common/ProjectCard.tsx
  packages/grant-explorer/src/features/common/SearchInput.tsx
  packages/grant-explorer/src/features/common/__tests__/SearchInput.test.tsx
  packages/grant-explorer/src/features/discovery/RoundStrategyBadge.tsx
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/grant-explorer/vitest.config.ts
  packages/round-manager/src/constants.ts
  packages/round-manager/src/context/application/BulkUpdateGrantApplicationContext.tsx
  packages/round-manager/src/context/application/usePayout.ts
  packages/round-manager/src/context/program/ReadProgramContext.tsx
  packages/round-manager/src/context/round/RoundContext.tsx
  packages/round-manager/src/features/api/AlloWrapper.tsx
  packages/round-manager/src/features/api/application.ts
  packages/round-manager/src/features/api/program.ts
  packages/round-manager/src/features/api/round.ts
  packages/round-manager/src/features/common/parseRoundDates.tsx
  packages/round-manager/src/features/program/CreateProgramPage.tsx
  packages/round-manager/src/features/program/ViewProgramPage.tsx
  packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
  packages/round-manager/src/features/round/ApplicationsToReview.tsx
  packages/round-manager/src/features/round/FundContract.tsx
  packages/round-manager/src/features/round/ViewApplicationPage.tsx
  packages/round-manager/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
  packages/round-manager/src/features/round/__tests__/ApplicationDirectPayout.test.tsx
  packages/round-manager/src/features/round/__tests__/ApplicationsApproved.test.tsx
  packages/round-manager/src/features/round/__tests__/ApplicationsToReview.test.tsx
  packages/round-manager/src/features/round/usePayouts.tsx
  packages/round-manager/tsconfig.json
  pnpm-lock.yaml
Labels: Feature Branch

#3410 Add Lukso/ Celo support
  packages/builder/src/actions/roundApplication.ts
  packages/builder/src/contracts/deployments.ts
  packages/builder/src/utils/RoundApplicationBuilder.ts
  packages/builder/src/utils/chains.ts
  packages/builder/src/utils/wallet.ts
  packages/common/package.json
  packages/common/src/allo/addresses/allo-v1.ts
  packages/common/src/allo/addresses/mrc.ts
  packages/common/src/allo/backends/allo-v2.ts
  packages/common/src/chain-ids.ts
  packages/common/src/chains.ts
  packages/common/src/graphql_fetch.ts
  packages/common/src/icons/celo-logo.svg
  packages/common/src/icons/lukso-logo.svg
  packages/common/src/index.ts
  packages/common/src/payoutTokens.ts
  packages/grant-explorer/public/logos/celo-logo.svg
  packages/grant-explorer/public/logos/cusd-logo.png
  packages/grant-explorer/public/logos/gcv.svg
  packages/grant-explorer/public/logos/gtc.svg
  packages/grant-explorer/public/logos/lukso-logo.svg
  packages/grant-explorer/public/logos/mkusd-logo.svg
  packages/grant-explorer/public/logos/power-pool.png
  packages/grant-explorer/public/logos/sei.png
  packages/grant-explorer/public/logos/usdglo-logo.svg
  packages/grant-explorer/public/logos/zksync-logo.svg
  packages/grant-explorer/src/app/chainConfig.ts
  packages/grant-explorer/src/features/api/utils.ts
  packages/round-manager/public/logos/celo-logo.svg
  packages/round-manager/public/logos/cusd-logo.png
  packages/round-manager/public/logos/lukso-logo.svg
  packages/round-manager/src/app/wagmi.ts
  packages/round-manager/src/context/application/usePayout.ts
  packages/round-manager/src/context/round/FundContractContext.tsx
  packages/round-manager/src/context/round/__tests__/ReclaimFundsContext.test.tsx
  packages/round-manager/src/features/api/__tests__/utils.test.ts
  packages/round-manager/src/features/api/application.ts
  packages/round-manager/src/features/api/contracts.ts
  packages/round-manager/src/features/api/utils.ts
  packages/round-manager/src/features/common/AddQuestionModal.tsx
  packages/round-manager/src/features/common/BaseSwitch.tsx
  packages/round-manager/src/features/common/__tests__/AddQuestionModal.test.tsx
  packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
  packages/round-manager/src/features/round/FundContract.tsx
  packages/round-manager/src/features/round/QuadraticFundingForm.tsx
  packages/round-manager/src/features/round/ReclaimFunds.tsx
  packages/round-manager/src/features/round/RoundApplicationForm.tsx
  packages/round-manager/src/features/round/ViewFundGrantees.tsx
  packages/round-manager/src/features/round/ViewRoundResults/ViewRoundResults.tsx
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
  packages/round-manager/src/features/round/ViewRoundStats.tsx
  packages/round-manager/src/features/round/__tests__/QuadraticFundingForm.test.tsx
  packages/round-manager/src/features/round/__tests__/RoundApplicationForm.test.tsx
  pnpm-lock.yaml
Labels: new network

#3331 Update UTC time to local time
  packages/common/package.json
  packages/common/src/index.ts
  packages/grant-explorer/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/common/parseRoundDates.tsx
  packages/round-manager/src/features/program/ViewProgramPage.tsx
  packages/round-manager/src/features/program/__tests__/ViewProgramPage.test.tsx
  packages/round-manager/src/features/round/ApplicationDirectPayout.tsx
  packages/round-manager/src/features/round/RoundDetailForm.tsx
  packages/round-manager/src/features/round/ViewApplicationPage.tsx
  packages/round-manager/src/features/round/ViewRoundPage.tsx
  packages/round-manager/src/features/round/ViewRoundSettings.tsx
  pnpm-lock.yaml
Labels: chore
